/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Primitivas.RedBlackTree;
import com.csvreader.CsvWriter;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.graphstream.graph.implementations.MultiGraph;
import org.graphstream.ui.view.Viewer;

/**
 *
 * @author fidel
 */
public class Interfaz extends javax.swing.JFrame {

    RedBlackTree arbol;
    private static MultiGraph graph;
    private static Viewer viewer;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    private void draw() {

        if (graph == null) {
            graph = new MultiGraph("Grafo");
        } else {
            graph.clear();
        }

        System.setProperty("org.graphstream.ui", "swing");
        System.setProperty("org.graphstream.ui.renderer", "org.graphstream.ui.j2dviewer.J2DGraphRenderer");

        graph.setAttribute("ui.quality");
        graph.setAttribute("ui.antialias");
        RedBlackTree.draw(arbol.getTreeRoot(), graph, arbol);
        if (viewer == null) {
            viewer = graph.display();
            viewer.setCloseFramePolicy(Viewer.CloseFramePolicy.HIDE_ONLY);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonCargarCsv = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        buttonAniadir = new javax.swing.JButton();
        buttonGuardar = new javax.swing.JButton();
        buttonBuscar = new javax.swing.JButton();
        Nombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JTextField();
        CedulaAgregar = new javax.swing.JTextField();
        CedulaEliminar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonCargarCsv.setText("Cargar CSV");
        buttonCargarCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCargarCsvActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCargarCsv, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 150, -1));

        buttonEliminar.setText("Eliminar Ciudadano");
        buttonEliminar.setEnabled(false);
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 190, 30));

        buttonAniadir.setText("Agregar Ciudadano");
        buttonAniadir.setEnabled(false);
        buttonAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAniadirActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAniadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 30));

        buttonGuardar.setText("Guardar");
        buttonGuardar.setEnabled(false);
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 150, -1));

        buttonBuscar.setText("Buscar");
        buttonBuscar.setEnabled(false);
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 190, 30));

        Nombre.setEnabled(false);
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 140, 20));

        Apellido.setEnabled(false);
        Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 140, -1));

        CedulaAgregar.setEnabled(false);
        CedulaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(CedulaAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 140, -1));

        CedulaEliminar.setEnabled(false);
        CedulaEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(CedulaEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 140, -1));

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel2.setText("Apellido");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel3.setText("Cedula ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel4.setText("Cedula");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCargarCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCargarCsvActionPerformed
        File fArchivoSeleccionado;
        JFileChooser seleccionarArchivo;
        seleccionarArchivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*CSV", "csv");
        seleccionarArchivo.setFileFilter(filtro);
        seleccionarArchivo.showOpenDialog(null);
        try {

            fArchivoSeleccionado = seleccionarArchivo.getSelectedFile();

            try (FileReader fr = new FileReader(fArchivoSeleccionado)) {
                BufferedReader br = new BufferedReader(fr);
                br.readLine();
                String sLine;
                boolean bFirst = true;
                while ((sLine = br.readLine()) != null) {
                    String[] saRegistro = sLine.split(",");
                    if (!bFirst) {
                        this.arbol.add(saRegistro[0], saRegistro[1], Integer.parseInt(saRegistro[2]));
                    } else {
                        this.arbol = new RedBlackTree(saRegistro[0], saRegistro[1], Integer.parseInt(saRegistro[2]));
                        bFirst = false;
                    }

                }
                if (!this.arbol.esVacia()) {
                    JOptionPane.showMessageDialog(null, "Archivo cargado correctamente", "Cargue OK", JOptionPane.INFORMATION_MESSAGE);
                    this.buttonAniadir.setEnabled(true);
                    this.buttonEliminar.setEnabled(true);
                    this.buttonGuardar.setEnabled(true);
                    this.buttonBuscar.setEnabled(true);
                    this.Nombre.setEnabled(true);
                    this.Apellido.setEnabled(true);
                    this.CedulaAgregar.setEnabled(true);
                    this.CedulaEliminar.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Revise que tenga elementos el csv aparte del encabezado", "Error!", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Revise que sea un archivo válido", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        this.arbol.printTree();
        draw();
    }//GEN-LAST:event_buttonCargarCsvActionPerformed

    private void buttonAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAniadirActionPerformed
        try {
            String firstName = Nombre.getText();
            String lastName = Apellido.getText();
            int identity = Integer.parseInt(CedulaAgregar.getText());
            if (!firstName.equals("") && !lastName.equals("")) {
                this.arbol.add(firstName, lastName, identity);
                JOptionPane.showMessageDialog(null, "Agregado correctamente", "OK", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Vuelva a intentar", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Verifique sus datos", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        Nombre.setText("");
        Apellido.setText("");
        CedulaAgregar.setText("");
        draw();
    }//GEN-LAST:event_buttonAniadirActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        try {
            int identity = Integer.parseInt(CedulaEliminar.getText());
            this.arbol.remove(identity);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Solo numeros", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        CedulaEliminar.setText("");
        draw();
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed

        try {
            CsvWriter csvwriter = new CsvWriter("newHabitantes.csv");
            String[] saEncabezado = {"Nombre", "Apellido", "CI"};
            csvwriter.writeRecord(saEncabezado);
            if (!this.arbol.esVacia()) {
                this.arbol.recorrerImprimir(csvwriter, this.arbol.getTreeRoot());
                csvwriter.close();
                JOptionPane.showMessageDialog(null, "Exito al escribir", "Ok!", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(null, "El arbol esta vacio", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Hubo problemas al guardar: " + ex.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonGuardarActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        try {
            int identity = Integer.parseInt(CedulaEliminar.getText());
            this.arbol.search(identity, graph);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Solo numeros", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        CedulaEliminar.setText("");
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoActionPerformed

    private void CedulaEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaEliminarActionPerformed

    private void CedulaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido;
    private javax.swing.JTextField CedulaAgregar;
    private javax.swing.JTextField CedulaEliminar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton buttonAniadir;
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonCargarCsv;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
